/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package java.application

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'java.application.greeting' plugin.
 */
class JavaApplicationPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("java.application.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
